<?php

namespace Database\Seeders;

use App\Models\StorefrontTemplate;
use Illuminate\Database\Seeder;

class StorefrontTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'id' => 'classic',
                'label' => 'Classic Commerce',
                'description' => 'A balanced storefront with a clear hero, featured products, and trust blocks.',
                'best_for' => 'Most shops',
                'preview' => 'balanced',
                'type' => 'json',
                'is_active' => false,
                'sort_order' => 10,
                'industries' => ['other', 'food_and_beverage', 'services'],
                'tone_tags' => ['friendly', 'balanced', 'simple'],
                'visual_tags' => ['classic', 'trust-led', 'product-focused'],
                'product_types' => ['physical', 'service'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['trustBadges', 'featuredProducts'],
                'origin' => 'platform',
                'generation_status' => 'inactive',
                'default_palette' => [
                    'primary' => '#1F6F5B',
                    'accent' => '#F4B860',
                    'background' => '#FFFFFF',
                    'surface' => '#F7FAF8',
                    'text' => '#10201B',
                    'muted' => '#64736E',
                    'border' => '#DCE7E1',
                ],
            ],
            [
                'id' => 'editorial',
                'label' => 'Editorial Brand',
                'description' => 'A more premium, story-led layout for lifestyle and beauty businesses.',
                'best_for' => 'Fashion, beauty, home',
                'preview' => 'editorial',
                'type' => 'json',
                'is_active' => false,
                'sort_order' => 20,
                'industries' => ['fashion_and_apparel', 'beauty_and_skincare', 'home_and_living'],
                'tone_tags' => ['premium', 'editorial', 'warm'],
                'visual_tags' => ['story-led', 'lifestyle', 'soft'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['brandStory', 'collectionFeature'],
                'origin' => 'platform',
                'generation_status' => 'inactive',
                'default_palette' => [
                    'primary' => '#7C3A2D',
                    'accent' => '#D8A48F',
                    'background' => '#FFFFFF',
                    'surface' => '#F8F3F0',
                    'text' => '#241613',
                    'muted' => '#75615B',
                    'border' => '#E8DAD5',
                ],
            ],
            [
                'id' => 'fashion_lookbook',
                'label' => 'Fashion',
                'description' => 'A clothing-brand homepage with campaign imagery, curated edits, and product drops.',
                'best_for' => 'Clothing brands',
                'preview' => 'lookbook',
                'type' => 'json',
                'sort_order' => 30,
                'industries' => ['fashion_and_apparel'],
                'tone_tags' => ['bold', 'editorial', 'modern'],
                'visual_tags' => ['lookbook', 'campaign-led', 'image-forward'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['featuredDrops', 'lookbookStory'],
                'origin' => 'platform',
                'generation_status' => 'active',
                'default_palette' => [
                    'primary' => '#111111',
                    'accent' => '#80131B',
                    'background' => '#FFFFFF',
                    'surface' => '#EEF0EF',
                    'text' => '#111111',
                    'muted' => '#6E6E6E',
                    'border' => '#E3E3E3',
                ],
            ],
            [
                'id' => 'beauty',
                'label' => 'Beauty',
                'description' => 'A polished beauty storefront for hair, skincare, bundles, and best-seller storytelling.',
                'best_for' => 'Beauty, hair, skincare',
                'preview' => 'beauty',
                'type' => 'json',
                'sort_order' => 40,
                'industries' => ['beauty_and_skincare'],
                'tone_tags' => ['premium', 'soft', 'polished'],
                'visual_tags' => ['editorial', 'warm', 'product-focused'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['bestSellers', 'routineFeature'],
                'origin' => 'platform',
                'generation_status' => 'active',
                'default_palette' => [
                    'primary' => '#6F2F2B',
                    'accent' => '#E6A79F',
                    'background' => '#FFF7F3',
                    'surface' => '#FFFFFF',
                    'text' => '#211313',
                    'muted' => '#80615C',
                    'border' => '#F0D6D0',
                ],
            ],
            [
                'id' => 'cosmetics',
                'label' => 'Cosmetics',
                'description' => 'A clean cosmetics storefront for skincare, serums, product storytelling, and ingredient-led trust.',
                'best_for' => 'Cosmetics, skincare',
                'preview' => 'cosmetics',
                'type' => 'json',
                'sort_order' => 45,
                'industries' => ['beauty_and_skincare'],
                'tone_tags' => ['natural', 'premium', 'clean', 'soft'],
                'visual_tags' => ['minimal', 'ingredient-led', 'product-focused'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['routineFeature', 'ingredientFeature'],
                'origin' => 'platform',
                'generation_status' => 'active',
                'default_palette' => [
                    'primary' => '#82934C',
                    'accent' => '#F7E7D3',
                    'background' => '#FFFFFF',
                    'surface' => '#F4F6F1',
                    'text' => '#172012',
                    'muted' => '#6E7564',
                    'border' => '#E2E6D9',
                ],
            ],
            [
                'id' => 'minimalistic',
                'label' => 'Minimalistic',
                'description' => 'A clean supplement-inspired storefront with soft neutrals, rounded product cards, and wellness storytelling.',
                'best_for' => 'Wellness brands',
                'preview' => 'minimal',
                'type' => 'json',
                'sort_order' => 50,
                'industries' => ['home_and_living', 'food_and_beverage', 'electronics', 'services', 'other'],
                'tone_tags' => ['minimal', 'calm', 'clean', 'warm'],
                'visual_tags' => ['soft', 'neutral', 'catalog-friendly'],
                'product_types' => ['physical', 'service'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['categoryHighlights', 'wellnessStory'],
                'origin' => 'platform',
                'generation_status' => 'active',
                'default_palette' => [
                    'primary' => '#073E3F',
                    'accent' => '#D99359',
                    'background' => '#FBFBDC',
                    'surface' => '#FFFFFF',
                    'text' => '#073E3F',
                    'muted' => '#5F7A6F',
                    'border' => '#D8DEC1',
                ],
            ],
            [
                'id' => 'bold_grid',
                'label' => 'Bold Product Grid',
                'description' => 'A product-forward template with stronger catalog emphasis.',
                'best_for' => 'Electronics, food, high-volume catalog',
                'preview' => 'grid',
                'type' => 'json',
                'is_active' => false,
                'sort_order' => 60,
                'industries' => ['electronics', 'food_and_beverage'],
                'tone_tags' => ['bold', 'direct', 'energetic'],
                'visual_tags' => ['grid', 'catalog-heavy', 'high-contrast'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'value_props', 'products', 'faq'],
                'optional_content_slots' => ['categoryGrid', 'dealBanner'],
                'origin' => 'platform',
                'generation_status' => 'inactive',
                'default_palette' => [
                    'primary' => '#0F4C81',
                    'accent' => '#F59E0B',
                    'background' => '#FFFFFF',
                    'surface' => '#F3F7FB',
                    'text' => '#102033',
                    'muted' => '#607085',
                    'border' => '#DCE7F2',
                ],
            ],
            [
                'id' => 'furniture-hardware',
                'label' => 'Furniture & Hardware',
                'description' => 'A premium furniture storefront with room collections, category grids, and editorial product storytelling.',
                'best_for' => 'Furniture, home decor',
                'preview' => 'furniture',
                'type' => 'json',
                'sort_order' => 55,
                'industries' => ['home_and_living'],
                'tone_tags' => ['premium', 'editorial', 'warm'],
                'visual_tags' => ['room-led', 'catalog-rich', 'image-forward'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'products'],
                'optional_content_slots' => ['categoryHighlights', 'roomCollections'],
                'origin' => 'platform',
                'generation_status' => 'active',
                'default_palette' => [
                    'primary' => '#2C2416',
                    'accent' => '#C4A574',
                    'background' => '#FAF7F2',
                    'surface' => '#FFFFFF',
                    'text' => '#2C2416',
                    'muted' => '#7A6E5E',
                    'border' => '#E8E0D4',
                ],
            ],
            [
                'id' => 'hair-and-fashion',
                'label' => 'Hair & Fashion',
                'description' => 'A beauty-forward storefront for hair extensions, textures, and fashion accessories with editorial styling.',
                'best_for' => 'Hair, extensions, fashion',
                'preview' => 'hair_fashion',
                'type' => 'json',
                'sort_order' => 56,
                'industries' => ['beauty_and_skincare', 'fashion_and_apparel'],
                'tone_tags' => ['editorial', 'premium', 'bold'],
                'visual_tags' => ['lookbook', 'texture-led', 'campaign-style'],
                'product_types' => ['physical'],
                'required_content_slots' => ['hero', 'about', 'products'],
                'optional_content_slots' => ['textureFeature', 'styleGallery'],
                'origin' => 'platform',
                'generation_status' => 'active',
                'default_palette' => [
                    'primary' => '#1A1410',
                    'accent' => '#D4A574',
                    'background' => '#FDF8F3',
                    'surface' => '#FFFFFF',
                    'text' => '#1A1410',
                    'muted' => '#7A6B5E',
                    'border' => '#EDE4D8',
                ],
            ],
        ];

        foreach ($templates as $template) {
            StorefrontTemplate::updateOrCreate(
                ['id' => $template['id']],
                array_merge(['is_active' => true], $template),
            );
        }
    }
}
